name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/deploy-pages@v4

